version: "3.7"

services:
  php8.1:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    image: phpdocker81
    container_name: phpdocker81
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf

#  app:
#    build:
#      context: ./docker/php/
#      dockerfile: Dockerfile
#    image: app-php81-apache
#    container_name: app-clean
#    restart: unless-stopped
#    working_dir: /var/www/
#    volumes:
#      - ./:/var/www/public
#    ports:
#      - '9011:80'
#    networks:
#      - network-project

#  db:
#    image: mysql:8.0
#    container_name: db-gerador-de-sistemas-base
#    restart: unless-stopped
#    environment:
#      MYSQL_DATABASE: ${DB_DATABASE}
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_USER: ${DB_USERNAME}
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
#    #volumes:
#    #  - ./docker-compose/mysql:/docker-entrypoint-initdb.d
#    networks:
#      - project-network

#  nginx:
#    image: nginx:1.17-alpine
#    container_name: nginx-gerador-de-sistemas-base
#    restart: unless-stopped
#    ports:
#      - "9003:80"
#    volumes:
#      - ./:/var/www
#      - ./docker/nginx:/etc/nginx/conf.d
#    networks:
#      - network-project

#  apache:
#    image: php:8.1-apache
#    container_name: apache-clean
#    ports:
#      - '8010:80'
#    volumes:
#      - ./:/usr/local/apache2/htdocs
#    networks:
#      - network-project

#networks:
#  network-project:
#    driver: bridge





#version: '3'
#
#services:
#  php8.1:
#    image: php:8.1
#    container_name: php8.1
#    ports:
#      - 9001:80
#    restart: always
#    volumes:
#      - /var/www/html:/var/www/html
#    links:
#      - db80


# Imagem Mysql Versão 8.0
#db80:
#  image: mysql:8.0
#  container_name: mysql8.0
#  command: --default-authentication-plugin=mysql_native_password
#  restart: always
#  ports:
#    - 3380:3306
#  environment:
#    - MYSQL_ROOT_PASSWORD=root
#  volumes:
#    - ./data-mysql-80:/var/lib/mysql
